### ISSUE TITLE
I noticed that there is no author info on the README.

### ISSUE THREAD

**Issue by hbruckman** [hbruckman/HelloWorldGitHub#1]
Greetings my fellow developers!

I noticed that there is no author info on the README. I wish to fix that, if you please.

I will be expecting your answer by the end of the day today.

Best regards,
Henry F. Bruckman Vargas, Ph.D.

**Comment by hbruckman** [comment]
Yeah! Sure! Go ahead! Thanxx!

**Comment by hbruckman** [comment]
❤

**Comment by hbruckman** [comment]
Go ahead! 👍

**Comment by jaddiel09** [comment]
lol

**Comment by CardehnTheWise** [comment]
I approve this messaje!!

**Comment by AdmiralUmbrella** [comment]
Sure!

**Comment by jaddiel09** [comment]
I need that issue done today asap

**Comment by jaddiel09** [comment]
your fired!

**Comment by CardehnTheWise** [comment]
Try finger butthole

**Comment by hbruckman** [comment]
Hey yo, guys and gals! I just finished my changes. Imma gonna let you check them out in my PR.

**Comment by hbruckman** [comment]
Done! ThankS!
